name: 80acrefarm
favicon: null
layout_spectrum: 0.4014839462470263
typography_spectrum: 0.17078558751381934
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.7085018598008901
  lightness: 0.39673356898128986
  saturation: 0.6177137256599963
  rhythmicContrast: 0.4578234546352178
purpose: []
